stages:
    - test

.test_template: &test_definition
    stage: test
    image: docker:latest
    variables:
        DOCKER_HOST: tcp://docker:2375
        DOCKER_DRIVER: overlay
    services:
        - docker:dind
    script:
        - apk update
        - apk add make git python py-setuptools
        - make PYTEST_ADDOPTS="-m 'standard or functional'" test-docker

test:f26:
    <<: *test_definition
    variables:
        DOCKER_IMAGE: fedora:26

test:latest:
    <<: *test_definition
    variables:
        DOCKER_IMAGE: fedora:latest

test:rawhide:
    <<: *test_definition
    variables:
        DOCKER_IMAGE: fedora:rawhide
