specfile_path: rebase-helper.spec
synced_files:
  - .packit.yaml
  - rebase-helper.spec
jobs:
  - trigger: release
    release_to:
      - master
  - trigger: pull_request
    release_to:
      - master
upstream_name: rebase-helper
package_name: rebase-helper
dist_git_url: https://src.fedoraproject.org/rpms/rebase-helper.git
checks:
  - name: simple-koji-ci
  - name: Fedora CI
