sudo: required
language: python
services: docker
env:
    - DOCKER_IMAGE=fedora:26
    - DOCKER_IMAGE=fedora:latest
    - DOCKER_IMAGE=fedora:rawhide
install: true
before_script:
    - |
        if [ "${TRAVIS_EVENT_TYPE}" = "cron" ]; then
            PYTEST_ADDOPTS="-m 'standard or functional or functional_long_running'"
        else
            PYTEST_ADDOPTS="-m 'standard or functional'"
        fi
script:
    - make PYTEST_ADDOPTS="${PYTEST_ADDOPTS}" test-docker
