sudo: required
language: python
services: docker
env:
    - DOCKER_IMAGE=fedora:26
    - DOCKER_IMAGE=fedora:latest
    - DOCKER_IMAGE=fedora:rawhide
before_install:
    # Update docker to allow using ARG in FROM (>= 17.05.0-ce)
    # https://github.com/moby/moby/blob/master/CHANGELOG.md
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
install: true
before_script:
    - |
        if [ "${TRAVIS_EVENT_TYPE}" = "cron" ]; then
            PYTEST_ADDOPTS="-m 'standard or functional or functional_long_running'"
        else
            PYTEST_ADDOPTS="-m 'standard or functional'"
        fi
script:
    - make PYTEST_ADDOPTS="${PYTEST_ADDOPTS}" test-docker
