sudo: required
language: python
services: docker
env:
    - DISTRO=fedora-26
    - DISTRO=fedora-latest
    - DISTRO=fedora-rawhide
install: true
before_script:
    - |
        if [ "${TRAVIS_EVENT_TYPE}" = "cron" ]; then
            PYTEST_ADDOPTS="-m 'standard or functional or functional_long_running'"
        else
            PYTEST_ADDOPTS="-m 'standard or functional'"
        fi
script:
    - make PYTEST_ADDOPTS="${PYTEST_ADDOPTS}" test-docker
